name = "projectEuler"
uuid = "be8e720f-9f08-4923-b63e-7b3f9c2808b5"
authors = ["eglucas_mtu.edu <eglucas@mtu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
